name: CustomExtensionConfig
description: Classes and method names to instrument
classes:
  - class_name: com.mulabs.java.WebFrontEndController
    method_name: methodDontExist
    config:
    - type: tag
      from: param
      param_index: 1
    - type: metric
      from: return
  - class_name: com.mulabs.java.WebFrontEnd
    method_name: myMethod
    config:
    - type: tag
      from: param
      param_index: 2
    - type: metric
      from: return